### ISSUE TITLE
Port to Firefox?

### ISSUE THREAD

**Issue by Hyperseeker** [sv3k/topscroll#10]
Hi!

I've been using TopScroll in Chrome for a long time, and it's become a habit to try and scroll pages that way: it just feels right.

Now, I'm thinking of Firefox, at least for a while. Apparently, you could publish most Chromium extensions to Firefox (or, at least, Firefox Quantum). I've tried to use TopScroll in Quantum in debug mode, to no avail: errors appear in relation to the manifest and script contents, which is above my paygrade.

So, I have to ask: could you possibly port the extenstion to Firefox? From the sound of it, [there are few obstacles to doing so](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension), since the API supported are mostly the same between the browser engines.

**Comment by sv3k** [comment]
That would be a good next step for the extension!

But I know nothing about Firefox extension development 😄 
So I can do it in two steps:

First is tinkering with extension code to make it work on Firefox and, more importantly, learn about differences between Firefox and Chrome.

Second is to do it right. I suppose the code has to be splitted into "core" universal part and browser-specific parts (Chromium and Firefox for now) with some configs, proxy code and build scripts. This splitting could be tricky for extension options page since it uses chrome-specific apis everywhere.

The link you provided should be really helpful here.

**Comment by FirebrandCoding** [comment]
For what it's worth, I tinkered enough with the extension code to make it appear in the Firefox addon manager (in development mode), to an extent where I was able to change options and have the selected parameters saved. Couldn't make it work proper (it didn't modify the pages), but it sounds like getting the extension to be recognized by FIrefox is the least tricky of the parts.

**Comment by sv3k** [comment]
So I finally switched to Firefox, and decided to spend some time on this.
Turned out, it works in Firefox with no changes in code at all! 😅
Enjoy: https://addons.mozilla.org/en-US/firefox/addon/top-scroll/
